### ISSUE TITLE
[Feature Request] Add INVITE_BROWSER support for shelteRPC

### ISSUE THREAD

**Issue by Milkshiift** [SpikeHD/shelter-plugins#35]
**Is your feature request related to a problem? Please describe.**
Currently, to accept an invite in a standalone client with shelteRPC you have to either log into Discord in a browser or send the link to a text channel in the client.

**Describe the solution you'd like**
arRPC sends an "INVITE_BROWSER" command when a Discord invite link is accepted in a browser. ShelteRPC could join the guild when such message is received.

**Additional context**
INVITE_BROWSER command would need to be implemented in rsRPC

**Comment by SpikeHD** [comment]
Prelim work is now [done in rsRPC](https://github.com/SpikeHD/rsRPC/compare/4b846a6107aa1deaf9d016dd21a4507c54810952..e5930cff75347061d57d28f12e7573755a0924d9), surprisingly tough to find a good function to hook/flux event to use to respond on the Shelter plugin side though, so that's not done yet.

This will also not be compatible with regular arRPC because they don't send `INVITE_BROWSER` (and other non-activity) events to the browser, but if they add that then I will change rsRPC and ShelteRPC to match to keep feature parity

**Comment by SpikeHD** [comment]
Along with some extra minor `rsRPC` fixes, this is now implemented in 48bfaa1882d0db6e4c31c3d15fe4da30eba3c36d!
